# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0004bca4723e5f82d3186cd489ff31c2"
name = "pragmatic-shipping-app"
handle = "pragmatic-shipping-app-2"
application_url = "https://lance-thanks-concrete-enrolled.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-bf6db4d7.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_inventory,read_orders,read_price_rules,read_products,write_customers,write_discounts,write_draft_orders,write_inventory,write_orders,write_price_rules,write_products"

[auth]
redirect_urls = [
  "https://lance-thanks-concrete-enrolled.trycloudflare.com/auth/callback",
  "https://lance-thanks-concrete-enrolled.trycloudflare.com/auth/shopify/callback",
  "https://lance-thanks-concrete-enrolled.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
