# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7b3e799d5d757210ef7c8c0dd194a8d7"
application_url = "https://obviously-enabling-wrong-spaces.trycloudflare.com"
embedded = true
name = "nuanced-ai-cross-upsell"
handle = "nuanced-ai-cross-upsell"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-bf6db4d7.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_inventory,read_orders,read_price_rules,read_products,write_customers,write_discounts,write_draft_orders,write_inventory,write_orders,write_price_rules,write_products"

[auth]
redirect_urls = [
  "https://obviously-enabling-wrong-spaces.trycloudflare.com/auth/callback",
  "https://obviously-enabling-wrong-spaces.trycloudflare.com/auth/shopify/callback",
  "https://obviously-enabling-wrong-spaces.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
