# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7b3e799d5d757210ef7c8c0dd194a8d7"
application_url = "https://ye-childrens-prominent-fees.trycloudflare.com"
embedded = true
name = "nuanced-ai-cross-upsell"
handle = "nuanced-ai-cross-upsell"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-bf6db4d7.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://ye-childrens-prominent-fees.trycloudflare.com/auth/callback",
  "https://ye-childrens-prominent-fees.trycloudflare.com/auth/shopify/callback",
  "https://ye-childrens-prominent-fees.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
