name: Development CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  develop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.13.1'  # Use the specific Node.js version

    - name: Install dependencies
      run: npm install

    - name: Set up environment variables
      run: |
        echo DATABASE_HOST=${{ secrets.DATABASE_HOST }} >> $GITHUB_ENV
        echo DATABASE_PORT=${{ secrets.DATABASE_PORT }} >> $GITHUB_ENV
        echo DATABASE_USER=${{ secrets.DATABASE_USER }} >> $GITHUB_ENV
        echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> $GITHUB_ENV
        echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> $GITHUB_ENV
        echo SHOPIFY_API_KEY=${{ secrets.SHOPIFY_API_KEY }} >> $GITHUB_ENV
        echo SHOPIFY_SECRET_KEY=${{ secrets.SHOPIFY_SECRET_KEY }} >> $GITHUB_ENV

    - name: Optionally set up database
      if: github.event.inputs.setup_db == 'true'
      run: node web/config/setupDatabase.js

    - name: Restart development server
      env:
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
        SHOPIFY_SECRET_KEY: ${{ secrets.SHOPIFY_SECRET_KEY }}
      run: |
        pm2 stop all || true
        npm run dev
